### ISSUE TITLE
BUG: Identation error 

### ISSUE THREAD

**Issue by harshakhmk** [IndianOpenSourceFoundation/dynamic-cli#105]
Getting an indentation error after running ```dynamic -s``` in ```arguments/search.py```
![identation-error](https://user-images.githubusercontent.com/56113657/120923870-6d1c0100-c6ee-11eb-8bf9-4992611d77be.png)
 I am on master branch with all latest changes

**Comment by pranavbaburaj** [comment]
Oh, Thank you for reporting the issue. 😄 . We will fix it. Thank you once again.

**Comment by harshakhmk** [comment]
Can I fix this error?

**Comment by GouravSardana** [comment]
Sure @harshakhmk . You can work on it. I'm assigning this issue to you.
