### ISSUE TITLE
Mistake in Readme

### ISSUE THREAD

**Issue by vaishnav-197** [IndianOpenSourceFoundation/dynamic-cli#11]

**Comment by vaishnav-197** [comment]
I do like to take it up

**Comment by GouravSardana** [comment]
@vaishnav-197 You can pick this item and send us a pull request

**Comment by deeppatel23** [comment]
If not done yet, may I take it up?

**Comment by GouravSardana** [comment]
@deeppatel23 It's not yet done. You can also pick that up.

**Comment by deeppatel23** [comment]
@GouravSardana This issue is solved
