### ISSUE TITLE
Dynamic CLI setup for Windows 

### ISSUE THREAD

**Issue by kaustubhgupta** [IndianOpenSourceFoundation/dynamic-cli#118]
## 💥 Proposal

As per issue #94 discussions, contributors are looking forward to windows support, and the `termos` package we are using is only implemented for Linux machines. 

Till the time we release a proper windows version, the contributors should be able to contribute to the code base. What if I tell you that you can do your development in a Linux environment and still use windows machines? **No, I am not talking about dual boot or virtualization.** It's WSL!

**Windows subsystem for Linux (WSL)** is a compatibility layer for running Linux binary executables natively on Windows 10, Windows 11, and Windows Server 2019. I think most of the Windows developers are using Windows 10 and it would be great news for them to use WSL as their development environment. 

I am using WSL2 for quite some time and I tried testing dynamic cli. It worked like a charm.

![image](https://user-images.githubusercontent.com/43691873/125242854-d8b74680-e30a-11eb-9bf2-810665f6e887.png)

I can create a quick demo resource/ text tutorial on setting up dynamic cli on Windows machines.

Let me know your thoughts. CC: @GouravSardana @sakshatl

**Comment by pranavbaburaj** [comment]
Yes, WSL is of course a great solution. But, we can't force our contributors to download pretty heavy software just to contribute to the project(1.82 GB is pretty heavy). But, contributors can use WSL if they wish to 🙂 . Thank you for recommending a solution 🤗 🙂

**Comment by kaustubhgupta** [comment]
> Yes, WSL is of course a great solution. But, we can't force our contributors to download pretty heavy software just to contribute to the project(1.82 GB is pretty heavy). But, contributors can use WSL if they wish to 🙂 . Thank you for recommending a solution 🤗 🙂

WSL is not much heavy, plus this is not only limited to dynamic CLI but it will support them in future projects also

**Comment by pranavbaburaj** [comment]
> > Yes, WSL is of course a great solution. But, we can't force our contributors to download pretty heavy software just to contribute to the project(1.82 GB is pretty heavy). But, contributors can use WSL if they wish to 🙂 . Thank you for recommending a solution 🤗 🙂
> 
> WSL is not much heavy, plus this is not only limited to dynamic CLI but it will support them in future projects also

Yes, that's also true 🙂

**Comment by GouravSardana** [comment]
For now we can adopt this plan but i don't think this will work longer. We have to remove the dependencies which is dependent upon OS

**Comment by GouravSardana** [comment]
Hey @kaustubhgupta , Are you working on this?

**Comment by kaustubhgupta** [comment]
I didn't got the confirmation on this, that's why I was waiting. Should I make this resource? If yes, then where to put this file and under which section should I link it in the readme.

P.S: Not related to the issue, I am not able to join the telegram group. The link is not working for me.

**Comment by GouravSardana** [comment]
Yup, You can get started on this. You can put in the installment section. Please mention only for windows. Other than that follow the above thing (pip install ...)


Try this link - https://t.me/joinchat/FjyKgz1w3ppiZjI1

**Comment by kaustubhgupta** [comment]
> Yup, You can get started on this. You can put in the installment section. Please mention only for windows. Other than that follow the above thing (pip install ...)
> 
> Try this link - https://t.me/joinchat/FjyKgz1w3ppiZjI1

okay, I will pull up the PR soon.

**Comment by kaustubhgupta** [comment]
Update: It might take a little longer time, I am quite busy these days.

**Comment by GouravSardana** [comment]
Take your time

**Comment by kaustubhgupta** [comment]
Closing this issue here, can be continued in #123
