### ISSUE TITLE
Add a new GIF in the Readme.md

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#122]
We need a new GIF for our readme. The previous one is quite old. We have new features as well with better UX

**Comment by GouravSardana** [comment]
Sure. Please do that. I'll assign it to you

**Comment by rohan26062001** [comment]
Okay

**Comment by pranavbaburaj** [comment]
![Untitled design](https://user-images.githubusercontent.com/70764593/135473377-ccbd2ba8-30e7-4e79-9dcb-710852523ba4.gif)
I happened to create a gif a few days ago.

**Comment by GouravSardana** [comment]
Pranav, It's just for the search. We need other params as well - api's req, notion, playbook

**Comment by pranavbaburaj** [comment]
> Pranav, It's just for the search. We need other params as well - api's req, notion, playbook

Oh yeah.

**Comment by rohan26062001** [comment]
![dynamic_cli](https://user-images.githubusercontent.com/74822378/135497497-d33ee55b-1acf-4208-bede-d13a0f13c10d.gif)
I uploaded this, can you please check

**Comment by GouravSardana** [comment]
Looks good can you please crop it down to only terminal ?

Don't be nervous. We all are iosf family. Feel free to ask anything ☺️

**Comment by rohan26062001** [comment]
![dynamic_cli](https://user-images.githubusercontent.com/74822378/135556506-a31d0dd9-d943-403c-bee5-7108bffd5895.gif)
Done Sir, can you please check?

**Comment by GouravSardana** [comment]
Looks good. Please go ahead and add it in the readme

**Comment by rohan26062001** [comment]
Actually, I've already updated it in my forked repository. Can you please tell me what to do now?

**Comment by pranavbaburaj** [comment]
You can go on and create a [pull request](https://github.com/IndianOpenSourceFoundation/dynamic-cli/compare)

**Comment by rohan26062001** [comment]
Done Sir
