### ISSUE TITLE
Inputs are still asking for tags

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#137]
Hey @pranavbaburaj ,

As per your PR, It should not ask for tags ? But I'm getting the tags as a input while running the dynamic

**Comment by GouravSardana** [comment]
I think this is quite confusing. We can mention somewhere that tags are optional.

**Comment by pranavbaburaj** [comment]
> Hey @pranavbaburaj ,
> 
> As per your PR, It should not ask for tags ? But I'm getting the tags as a input while running the dynamic

The user will be prompted to add tags. But, the user can leave it blank.

**Comment by GouravSardana** [comment]
But we can mentioned somewhere that this is option like tag (Optional)
