### ISSUE TITLE
Security Hotspot

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#142]
Hey Team,

Can someone please check this security hotspot [here](https://sonarcloud.io/project/security_hotspots?id=IndianOpenSourceFoundation_dynamic-cli&sinceLeakPeriod=true). It seems we are calling os.system. Can we please remove this? It's not destructive but still we have to remove this.

Anyone can pick and see why we are using that and what other options we have to replace this!

cc @pranavbaburaj

**Comment by pranavbaburaj** [comment]
I tested the app after commenting out the `os.system` call and it works fine. I think we can remove that from the file.

**Comment by GouravSardana** [comment]
Sure. Go ahead and raise a PR
