### ISSUE TITLE
Duplicate Entry - BUG

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#144]
Hey Team,

We are saving the data to playbook from utilities but I found this same thing in the search.py . I don't think we are using it because the line which are printing doesn't match to this search.py string.

Can someone check this thing [here](https://sonarcloud.io/project/issues?id=IndianOpenSourceFoundation_dynamic-cli&open=AX3N3DVTVwr6gt1dCHdw&resolved=false&types=BUG) ?

cc @pranavbaburaj

**Comment by GouravSardana** [comment]
I don't think this is useful -
 `<html>
<body>


colored(
--
111 |   |   | f"\U0001F604 Answers successfully saved into {filename}",
112 |   |   | "green",
113 |   |   | ),
114 |   |   | colored(
115 |   |   | "\U0001F604 Answers successfully saved into" + filename, "green"


</body>
</html>`

And this is the original string which we are printing while adding it to playbook in utilities - 

`self.playbook_content = content
 console.print("[green] Question added to the playbook")`

**Comment by GouravSardana** [comment]
Anyways, I fixed it [here](https://github.com/IndianOpenSourceFoundation/dynamic-cli/commit/f3c7acb1ce9440871be13e5594dead939188fdf4)

**Comment by pranavbaburaj** [comment]
Nice thanks. Sorry for the delay, I didn't get time to look at GitHub today. I was preparing for exams.

**Comment by GouravSardana** [comment]
Np buddy. Prepare for your exams. All the best from our community:)

**Comment by pranavbaburaj** [comment]
thanks :)
