### ISSUE TITLE
StackOverflow Query does not contain tags even if entered

### ISSUE THREAD

**Issue by kushshiv** [IndianOpenSourceFoundation/dynamic-cli#148]
# Issue :
StackOverflow Query does not contain tags even if entered. It should be an optional field. And should be included if Tags are entered by user. But currently it's not there in query.

# Screenshot:
|        Tags not Entered         |          Tags Entered           |
| :---------------------: | :------------------------: |
| <b>![Screen Shot 2022-01-08 at 3 15 31 PM](https://user-images.githubusercontent.com/33164379/148639792-3c8eed24-5199-499b-ad5f-b9d9baa89f1c.png)</b> | <b>![Screen Shot 2022-01-08 at 3 15 44 PM](https://user-images.githubusercontent.com/33164379/148639799-673a0812-e7dd-490d-b4ea-712624f63fa3.png)</b> |

**Comment by pranavbaburaj** [comment]
Well, if I'm correct. the search result doesn't change. So i guess its not a problem

**Comment by GouravSardana** [comment]
I think @pranavbaburaj made this tag optional. If you doesn't enter the tag, It'll still show the result

**Comment by pranavbaburaj** [comment]
> I think @pranavbaburaj made this tag optional. If you doesn't enter the tag, It'll still show the result
Yes, removing it doesnt make a difference in the result.

**Comment by kushshiv** [comment]
> I think @pranavbaburaj made this tag optional. If you doesn't enter the tag, It'll still show the result
>> Yes, removing it doesnt make a difference in the result.

yes for sure it shows the result... But my query is if we enter the tag, it should be there in the query:
![image](https://user-images.githubusercontent.com/33164379/148671091-3bc27bb1-3b84-4217-981a-a4fac5bbf934.png)

If you see in this query params `tagged=` remains null even if tags are entered by the user (Here I entered 'python' as tag but its not there in query param)...
Optional means, if we enter the tag it should be included in `tagged` query params right...??
Please correct me If I am thinking in wrong direction...

**Comment by GouravSardana** [comment]
@pranavbaburaj you removed the tag #136

**Comment by GouravSardana** [comment]
May be it’s by chance you removed it

**Comment by kushshiv** [comment]
# ask question
    for each_query in queries:
        # Be careful if there are
        # KeyBoard Interrupts or EOErrors
        try:
            prompt = Prompt(str(each_query)).prompt()
            if each_query == "Tags":
                continue
            if prompt.strip() == "": 
                SearchError(
                    "\U0001F613 Input data empty", "\U0001F504 Please try again "
                )   
                sys.exit()
        except:
            sys.exit()
  
        query_solutions.append(prompt)

Hmm... seems in the below line, continue moved to the next iteration without executing `query_solutions.append(prompt)` in case of Tags...

    if each_query == "Tags":
        continue

**Comment by pranavbaburaj** [comment]
> > I think @pranavbaburaj made this tag optional. If you doesn't enter the tag, It'll still show the result
> > > Yes, removing it doesnt make a difference in the result.
> 
> yes for sure it shows the result... But my query is if we enter the tag, it should be there in the query: ![image](https://user-images.githubusercontent.com/33164379/148671091-3bc27bb1-3b84-4217-981a-a4fac5bbf934.png)
> 
> If you see in this query params `tagged=` remains null even if tags are entered by the user (Here I entered 'python' as tag but its not there in query param)... Optional means, if we enter the tag it should be included in `tagged` query params right...?? Please correct me If I am thinking in wrong direction...

Oh. my bad. Can you work on a fix on this or should I?

**Comment by kushshiv** [comment]
> > > I think @pranavbaburaj made this tag optional. If you doesn't enter the tag, It'll still show the result
> > > > Yes, removing it doesnt make a difference in the result.
> > 
> > 
> > yes for sure it shows the result... But my query is if we enter the tag, it should be there in the query: ![image](https://user-images.githubusercontent.com/33164379/148671091-3bc27bb1-3b84-4217-981a-a4fac5bbf934.png)
> > If you see in this query params `tagged=` remains null even if tags are entered by the user (Here I entered 'python' as tag but its not there in query param)... Optional means, if we enter the tag it should be included in `tagged` query params right...?? Please correct me If I am thinking in wrong direction...
> 
> Oh. my bad. Can you work on a fix for this or should I?


I will check and will raise PR...

**Comment by pranavbaburaj** [comment]
Thanks :)
