### ISSUE TITLE
Having Issue with Installation

### ISSUE THREAD

**Issue by Harshil-Jani** [IndianOpenSourceFoundation/dynamic-cli#156]
I have been trying to install Dynamic CLI as per developers guidelines given, but when I ran `dynamic -v` it throwed some traceback call.
```
Traceback (most recent call last):
  File "/usr/bin/dynamic", line 33, in <module>
    sys.exit(load_entry_point('dynamic-cli', 'console_scripts', 'dynamic')())
  File "/usr/bin/dynamic", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: dynamic-cli
```

I am using `Python 3.8.10`.
I even tried manually installing importlib-metadata using  `pip3 install importlib-metadata` but this says
 `Requirement already satisfied: importlib-metadata in /usr/lib/python3/dist-packages (1.5.0)
`

**Comment by GouravSardana** [comment]
Hey @Harshil-Jani ,

Thanks for putting this issue out. I tried in my local again to install the dynamic from fresh. I didn't get the error as such

`(temp) gourav@LAPTOP-PHS5P97J:~/ubuntu$ dynamic -v`
`Dynamic-CLI version 0.1.0`

I'm also using python 3.8.10. Can you specify which OS you're using ? We currently support linux based OS and Mac. For window, you have to install WSL to make our dynamic cli works. Please let me know if you need any help

**Comment by GouravSardana** [comment]
Maybe it's conflicting with your local packages which are installed. You can try using virtualenv and install dynamic in the virtual env

**Comment by Harshil-Jani** [comment]
> Can you specify which OS you're using ? We currently support linux based OS and Mac.

I am using Ubuntu 20.04 LTS

>Maybe it's conflicting with your local packages which are installed. You can try using virtualenv and install dynamic in the virtual env

Oh Okay. I will be looking into this and let you know if it works or not.

**Comment by GouravSardana** [comment]
Please lemme know if you need more help else we’ll close this issue

**Comment by Harshil-Jani** [comment]
@GouravSardana  I lastly used `sudo pip3 install dynamic-cli` but found no soultion to existing problem. So, If you find any solution to that please let me know. I have tried by changing some Paths but it  didn't worked.

**Comment by GouravSardana** [comment]
Try installing in an environment variable

**Comment by sahilsuman933** [comment]
Hey @Harshil-Jani I am using Ubuntu 21.10 and Python Version 3.9.7 and it is working great. 

I also faced the issue at last step, it was due to permission issue. Which you can fix it by adding sudo before it.

Here is the exact command: `sudo pip3 install -e . `

**Comment by Harshil-Jani** [comment]
Woahhhh ! Really missed on that. Thankyou so much @sahilsuman933 !! It worked

**Comment by sahilsuman933** [comment]
@Harshil-Jani You are welcome :D
