### ISSUE TITLE
Add new GIFS for DynamicCLI readme

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#158]
We want to add new GIFs for our dynamic CLI in our readme just to make it easier for others to see what features we have in our CLI. Those GIFs should be in proper structure and will not contain any other irrelevant data

**Comment by GouravSardana** [comment]
GIFs for -
- APIs testing -> GET, POST
- Dynamic Search
- saving to the playbook
- Retrieving from Playbook

**Comment by sahilsuman933** [comment]
@GouravSardana Can I work on this issue?

**Comment by GouravSardana** [comment]
Sure

**Comment by sahilsuman933** [comment]
@GouravSardana could you please assign this issue to someone else

**Comment by GouravSardana** [comment]
No issues. Thanks for the update. This is open now !

**Comment by shreya024** [comment]
Hey @GouravSardana I would like to work on this issue

**Comment by GouravSardana** [comment]
Sure @shreya024 go ahead

**Comment by shreya024** [comment]
> Sure @shreya024 go ahead

It is required to create 4 separate gifs for the 4 functionalities correct? And let me know where exactly should I add them in the README. Also kindly assign

**Comment by GouravSardana** [comment]
Yes 4 GIF(search, playbook, GET, POST) and you can paste it in the readme where we have our previous GIF. 
Please make a GIF which is clearly visible and specify in the readme
