### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by itsIapetus** [IndianOpenSourceFoundation/dynamic-cli#16]
## 📚 Documentation

I would like on work on this under GSSoC, I would like to update the Readme, to make it easier for the students to see how they can contribute, from forking the project to creating a pull request. If this is okay, kindly assign it to me, otherwise would you create other issues?

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/IndianOpenSourceFoundation/dynamic-cli/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by GouravSardana** [comment]
@itsIapetus Sure. You can work on it
