### ISSUE TITLE
Test Cases - Write Unit test for our POST API feature

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#160]
As a developer, I want to write a unit test for POST API feature in our CLI. This should be a python test. Make a new folder named "TEST" and make a file according to your test name

**Comment by adii21-Ux** [comment]
Hi @GouravSardana I would like to work on this one

**Comment by GouravSardana** [comment]
Go ahead and work on it. I’m assigning it to you

**Comment by adii21-Ux** [comment]
Hello @GouravSardana can you tell how to specify json data in terminal. I am trying to write cases for both options I wrote a test case for second one but having input issues with second
![Screenshot from 2022-03-15 13-12-58](https://user-images.githubusercontent.com/88366673/158329862-ef0c985f-79b6-4078-a780-c8e38c0182cf.png)

**Comment by GouravSardana** [comment]
@adii21-Ux for the first one you need to pass the json in a single line just like curl
