### ISSUE TITLE
$ signs are getting copied while copying  commands from readme

### ISSUE THREAD

**Issue by shivankar-p** [IndianOpenSourceFoundation/dynamic-cli#169]
## 📚 Documentation

I think dollar signs can be removed from codeblocks of readme. It's annoying to encounter `$: command not found` error everytime when starting out with the initial setup.

I would also like to point that in Developer installation section command 3 and 4's order should be interchanged.

**Comment by GouravSardana** [comment]
cc @PradyumnaKrishna

**Comment by peb-peb** [comment]
@shivankar-p yeah, removing the `$` would be a good idea as it would allow contributors to directly copy-paste these commands.

> I would also like to point that in Developer installation section command 3 and 4's order should be interchanged.

I checked it now, and yeah, they should be switched.

**Comment by sinha-toyeesh** [comment]
@GouravSardana I would like to work on this as a GSSOC contributor.

**Comment by GouravSardana** [comment]
Go ahead and Please work on it

**Comment by shivankar-p** [comment]
Also in arguments section -d(debug) option was mentioned. I was getting `dynamic: error: unrecognized arguments: -d` this error.

**Comment by GouravSardana** [comment]
As per my understanding “d” is not there
