### ISSUE TITLE
Unable to run Dynamic-CLI using terminal [Using Source Code]

### ISSUE THREAD

**Issue by sahilsuman933** [IndianOpenSourceFoundation/dynamic-cli#178]
Issue: 
I am not able to run dynamic cli directly using terminal. It is working fine using pycharm but not with the terminal. It is showing dynamic module is not found. 

Screenshot of the Issue:
![image](https://user-images.githubusercontent.com/34382211/159948388-2fe73445-9afe-4506-9e66-025f3bb166b8.png)

System Details:
![Screenshot_20220324_204419](https://user-images.githubusercontent.com/34382211/159948729-8ebe5fcc-c044-4656-969c-278803a31054.png)

Python Version: Python 3.10

**Comment by pranavbaburaj** [comment]
![image](https://user-images.githubusercontent.com/70764593/159956887-413020b3-e318-4b03-b551-91ce41550def.png)
Not sure why, but it works for me

**Comment by sahilsuman933** [comment]
@pranavbaburaj just uninstall the dynamic cli using pip command then run it from the source code. Then I am sure you will face that issue.

**Comment by pranavbaburaj** [comment]
> @pranavbaburaj just uninstall the dynamic cli using pip command then run it from the source code. Then I am sure you will face that issue.
> 
> Like I am pretty sure you installed it through pip command too.

Should prolly be fixed in #179. Please  see whether the issue persists.

**Comment by sahilsuman933** [comment]
> > @pranavbaburaj just uninstall the dynamic cli using pip command then run it from the source code. Then I am sure you will face that issue.
> > Like I am pretty sure you installed it through pip command too.
> 
> Should prolly be fixed in #179. Please see whether the issue persists.

Okay Boss!
