### ISSUE TITLE
Fixed Greeting.yaml

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#18]
Greeting.yaml build is failing while someone sends a pull request. Anybody can pick this up and fix this.

You can find the greeting.yaml [here](https://github.com/IndianOpenSourceFoundation/dynamic-cli/blob/master/.github/workflows/greetings.yml)

**Comment by SwarupKharul** [comment]
hey! I am a GSSoC participant, i would like to solve this bug. Please assign me this issue!

**Comment by SwarupKharul** [comment]
I have made the necessary changes, but it is showing an error -' Resource not accessible by integration' when I make the PR

**Comment by Akash20x** [comment]
Hey @SwarupKharul I just made small silly change with your pull request and it worked

**Comment by GouravSardana** [comment]
Fixed #26
