### ISSUE TITLE
Improve contributing.md

### ISSUE THREAD

**Issue by metabiswadeep** [IndianOpenSourceFoundation/dynamic-cli#188]
## 📚 Documentation

Contributing.md has many grammatical errors. Improve the aforementioned file to make it easier for users to understand the guidelines for contributing to this project.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/IndianOpenSourceFoundation/dynamic-cli/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

I want to work on this issue as a part of GSSoC 23. Please assign this issue to me.

**Comment by yyuvraj54** [comment]
I will be very much delighted if i get a chance to contribute to this project , please assign this task to me under GSSoC '23

**Comment by pawankrgithub** [comment]
I want to work on this issue as a part of GSSoC 23. Please assign this issue to me.

**Comment by aditya-bagla** [comment]
Hi ,
Aditya Bagla ( GSSOC'23 contributor ) 
I would like to contribute on this issue . Can you please assign to me ?

**Comment by GouravSardana** [comment]
Sure. Anyone can work on it

**Comment by metabiswadeep** [comment]
> Sure. Anyone can work on it

I would like to work on it as a part of GSSoC 23. Please assign this issue to me @GouravSardana .

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
