### ISSUE TITLE
Codacy Integration

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#19]
We can have a Codacy integration in this project. So that before merging it will automatically analyze the quality of the code.

Learn more about Codacy [here](https://github.com/marketplace/codacy)

**Comment by SwarupKharul** [comment]
hey! I am a GSSoC participant, I would like to integrate codacy to this project. Please assign me this issue.

**Comment by Komal-99** [comment]
Yes I have read the Contribution guidelines
I would like to work on this codacy integration feature, Kindly assign it to me
Thanks

**Comment by feni-katharotiya** [comment]
@GouravSardana Hello, I am gssoc participant and would like to work on this issue.

**Comment by Siddhant-K-code** [comment]
@SwarupKharul  @Komal-99  @feni-katharotiya  Please share your approach, how would you implement this feature?

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by Sloth-Panda** [comment]
@GouravSardana can I work on this too?

**Comment by GouravSardana** [comment]
sure @Sloth-Panda

**Comment by honeybhardwaj** [comment]
hi @GouravSardana , to setup codacy i need rights so that i can setup it on this repo ryt?

**Comment by anshsrtv** [comment]
@GouravSardana Are you sure we need a YAML configuration file for Codacy? I checked the documentation for Codacy and couldn't find a reference to it.

**Comment by honeybhardwaj** [comment]
@GouravSardana  hi , don't you think you should even turn on the option of status check ,annothions and summary for better understanding during pull request and we ll also maintain code quality by that ??
![Screenshot from 2021-03-29 01-57-41](https://user-images.githubusercontent.com/51120790/112767113-7a53aa00-9032-11eb-907f-4f4a3020ec61.png)

**Comment by Siddhant-K-code** [comment]
Yes, it will be good if an owner of the repo. will integrate it with the project. 

OR 

We Can use this GitHub action [Codacy Analysis CLI](https://github.com/marketplace/actions/codacy-analysis-cli)

**Comment by GouravSardana** [comment]
@Siddhant-K-code You can add this Codacy Analysis CLI in our github workflow
