### ISSUE TITLE
code of conduct file

### ISSUE THREAD

**Issue by Sloth-Panda** [IndianOpenSourceFoundation/dynamic-cli#20]
## 📚 Documentation

(A clear and concise description of what the issue is.)
There is no code of conduct file explaining all the rules that should be followed while contributing to a project so would like to add one  under gssoc

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/IndianOpenSourceFoundation/dynamic-cli/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

**Comment by Sloth-Panda** [comment]
@GouravSardana can you please add "level0/ level1/ level2/ level3" any of the tags to the issue and pr along with "gssoc21"as per gssoc guidelines
else they wont be counted

**Comment by Sloth-Panda** [comment]
@GouravSardana can you please add gssoc21 label to this issue

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me
