### ISSUE TITLE
Change the layout of search results

### ISSUE THREAD

**Issue by anshsrtv** [IndianOpenSourceFoundation/dynamic-cli#33]
## 🚀 Feature

We want to display the search results in an organized manner. Hence, we need to change to the following format to display the results:
- For the most upvoted result:
  - Desc:
  - Ans:
  - Snippet:

- For the rest of the results:
  - Question title - URL

## Motivation

Currently, as shown in the screenshot below, the results aren't displayed in an organized manner and it's difficult to get the right results.

![image](https://user-images.githubusercontent.com/49693160/111129800-83596b80-859c-11eb-871c-5ea8cc77d3cb.png)
## Pitch

This feature, if implemented, would allow users to get instant access to the most upvoted answer in the same way as on the StackOverflow website.

**Comment by NamamiShanker** [comment]
@anshsrtv I can work on this issue

**Comment by anshsrtv** [comment]
@GouravSardana Please assign this issue to @NamamiShanker. Also, add the GSSOC tags.

**Comment by Nishayadav-bit** [comment]
Hey,
i'm a GSSOC'21 participant
Can i work on this issue

**Comment by anshsrtv** [comment]
Hi @Nishayadav-bit, Glad to hear that but this issue has already been assigned to @NamamiShanker. You can try solving #39, if you want.

**Comment by NamamiShanker** [comment]
Hi @anshsrtv . I have have done the changes so that the output is as you mentioned. Please check the image and suggest any changes. There is some problem in my bash terminal. The red lines print in a wierd way. 

![terminal_ss](https://user-images.githubusercontent.com/26577306/112718117-f1941b80-8f16-11eb-89fc-fca9bbab7cbe.png)

**Comment by anshsrtv** [comment]
@NamamiShanker It looks perfect ✨Please raise a PR for the same. The red line issue will be solved in #61.
