### ISSUE TITLE
Add emojis in CLI

### ISSUE THREAD

**Issue by anshsrtv** [IndianOpenSourceFoundation/dynamic-cli#39]
## 💥 Proposal: Emoji in CLI 

We can add relevant emojis in the CLI like minikube (Kubernetes). Check the screenshot below for reference:

<img src="https://raw.githubusercontent.com/kubernetes/minikube/master/site/static/images/screenshot.png" width="575" height="322" alt="screenshot">

**Comment by NamamiShanker** [comment]
@anshsrtv Yeah it will be cool! Can I work on this feature? I am a GSSOC participant.

**Comment by pranavbaburaj** [comment]
Most of the StackOverflow answers do not contain emojis

**Comment by GouravSardana** [comment]
@pranavbaburaj Not for StackOverflow but to improve our way to display the answers. If you have some other suggestions then we can try that too

**Comment by guptaaastha** [comment]
I have some ideas in mind and would like to experiment and try to work on this idea. Can you please assign this issue to me.

**Comment by anshsrtv** [comment]
We are excited to see your ideas get in shape!
