### ISSUE TITLE
AttributeError: module 'main' has no attribute 'search_obj'

### ISSUE THREAD

**Issue by devansh-07** [IndianOpenSourceFoundation/dynamic-cli#40]
Running **`dynamic -s`** after following installation instructions throws **`AttributeError`**.

![Screenshot from 2021-03-17 19-47-52](https://user-images.githubusercontent.com/53042477/111482291-c57bdc00-8759-11eb-96a4-3b72b300d606.png)

**Comment by pranavbaburaj** [comment]
Are you running the latest code??

**Comment by devansh-07** [comment]
Yes, I'm running the latest version.

**Comment by devansh-07** [comment]
I'd like to fix this.

**Comment by pranavbaburaj** [comment]
I don't think you are running the latest code, because the `search_obj` function was completely replaced with `search_flag `

**Comment by devansh-07** [comment]
It was replaced but not completely. _console_scripts_ entry point in **`setup.py`** still contains `search_obj` which throws this error.

**Comment by pranavbaburaj** [comment]
oh, ok 😄 . Thank you

**Comment by pranavbaburaj** [comment]
I guess I fixed it

https://github.com/IndianOpenSourceFoundation/dynamic-cli/pull/42

**Comment by GouravSardana** [comment]
@devansh-07 Can you take a pull and see if it works ?

**Comment by devansh-07** [comment]
Yes, It is working now.
