### ISSUE TITLE
Travis-CI Integration

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#46]
Integrate Travis CI with our dynamic-cli and add relevant build (pass/fail) icon in the readme as well.

For more information about Travis click [here](https://travis-ci.com/)

**Comment by aaryanrr** [comment]
Someone with the write access to this repository has to register on [Travis](https://travis-ci.org/) using GitHub and then activate the Webhook for this repository or in other words activate the CI Integration for this repository. Then I'll push a `.travis.yml` file that will trigger the build each time a PR is merged.
Also, as we do not have any tests currently for this library so what do you want to test in the build process?

**Comment by GouravSardana** [comment]
@aaryanrr I opened one issue #50 to write the test for this tool. If somebody picks that up then I'll activate the webhook for this repository and you can work on yaml file
