### ISSUE TITLE
Add a new args called --new to create a question on StackOverFlow

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#47]
We don't have any feature where we can add a new question on Stackoverflow using our Dynamic-cli.

Here are some details: - 
Example - 
1. dynamic --new
It will open up the default web browser and open StackOverflow in it with this [link](https://stackoverflow.com/questions/ask)

2. dynamic --new [title] [desc]
It will open up the default browser but with all the relevant fields filled already like title and description.

**Comment by asadafasab** [comment]
Can I work on this issue?

Filing up description/body using URL [query](https://meta.stackoverflow.com/questions/385508/is-there-a-way-to-pre-fill-the-body-of-a-new-question) is not that simple.

**Comment by GouravSardana** [comment]
@asadafasab Sure. You can work on this issue. Yeah prefilled data part is challenging

**Comment by GouravSardana** [comment]
We can pre-filled only titile @asadafasab
