### ISSUE TITLE
Setup your own custom Stackoverflow api key

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#48]
In our dynamic cli, we are using one default API key. We can have an option where the user can set his own custom API key rather than using our own.

@pranavbaburaj Can talk about it more!

**Comment by yasht01** [comment]
Hey! Can I work on this issue?

**Comment by anshsrtv** [comment]
Sure @yasht01

**Comment by yasht01** [comment]
Hey @pranavbaburaj I am kind of stuck as to where is the default API key is present in the source code. I looked in the `utility.py` file and I noticed the `search_content_url` making the API calls. Can you point out to the location of the API key?

**Comment by pranavbaburaj** [comment]
@yasht01, The project is using the public StackExchange API which does not require an API key. But, if you want to add a question completely via the CLI, we need to authenticate using the StackExchange Oauth API. I think that is what this issue is all about. You can read more about it [here](https://api.stackexchange.com/docs/authentication).

Please correct me If I am wrong 🙂 .

**Comment by yasht01** [comment]
@pranavbaburaj The documentation mentions the use of `client_id` for user authentication. This [answer](https://meta.stackoverflow.com/questions/261452/what-is-client-id-in-the-stack-overflow-oauth-api) mentions that we would have to register our application on [this](https://stackapps.com/apps/oauth/register) link. What should I do next?

**Comment by GouravSardana** [comment]
@pranavbaburaj Yes, you are correct. This will use the public API for fetching the result. We are thinking to separate the API to a different file called apiEndpoint.json or some different format.

**Comment by yasht01** [comment]
Hey @pranavbaburaj can I go ahead and register this app on Stack Apps for getting the `client_id`?

**Comment by GouravSardana** [comment]
sure. Goahead
