### ISSUE TITLE
Implement dynamic --version or -V

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#49]
We want an args where we can display our dynamic-cli version.

For example:-

- dynamic --version / dynamic -V 
It will give the version as 0.1 by default and when we published on PyPI then it will show up the new released version

**Comment by chaudharypraveen98** [comment]
I am a gssoc participant and I want to contribute to it.

**Comment by GouravSardana** [comment]
It should be like this - 
gourav@gourav:~$ dynamic --version
Dynamic-CLI version 0.1
