### ISSUE TITLE
Greeting.yaml checks fails for every pull request for the first time

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#67]
We added an action when somebody sends a pull request then one of our action is failing for the first time and when contributors will send one more commit in the same pull then it works.

For example - 
- Gourav sends a pull request - Greeting.yaml check will fail.

- Add a new commit - Remove extra spaces or anything

- In the same pull request - Greeting.yaml check will pass.

You can send us a test PR and see it live :)

**Comment by GouravSardana** [comment]
The FIle can be find [here](https://github.com/IndianOpenSourceFoundation/dynamic-cli/blob/master/.github/workflows/greetings.yml)

**Comment by himanshu007-creator** [comment]
ill test it.

**Comment by himanshu007-creator** [comment]
> > The FIle can be find [here](https://github.com/IndianOpenSourceFoundation/dynamic-cli/blob/master/.github/workflows/greetings.yml)
> 
> I have used it and in my repo, [it](https://github.com/himanshu007-creator/SFC-foundations/blob/master/.github/workflows/blank.yml) works fine. I would like to send a PR for this one🙂

 Should I send a PR to make it work?

**Comment by GouravSardana** [comment]
@himanshu007-creator Yes you can send a PR. I think my mistake this issue got closed
