### ISSUE TITLE
Implement GET in dynamic to get the response from an API

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#75]
This feature will include the following things - 

1. Once a user will enter dynamic -GET, it will ask for a URL to put and the default URL would be 127.0.0.1:8000 and it will ask for the end point or you can put directly in the URL itself
2. It will build on top of [CURL](https://github.com/curl/curl).
3. Output will get in JSON with proper syntax highlighter.

Example - 
dynamic -GET
Enter the URL - [press enter - default would be 127.0.0.1:800]

Trying (loading emoji) 

```
{
json result;
}
```

**Comment by yasht01** [comment]
Hey, can I work on this issue?

**Comment by yasht01** [comment]
Hey, where should I add the relevant code in `utility.py` or `search.py`?

**Comment by anshsrtv** [comment]
Please make a new file and add your code there. Yes, you can use `requests` library.

**Comment by yasht01** [comment]
@GouravSardana will the user give the endpoint only when `127.0.0.1:8000` is the URL or the user will always give the endpoint?

**Comment by GouravSardana** [comment]
@yasht01 Just to be clear endpoint is basically that comes after '/'
For example - I need to get the users from a URL called 127.0.0.1:8000 and the endpoint is /users

So, the Combined URL would be 127.0.0.1:8000/users

**Comment by GouravSardana** [comment]
For you next question - 

We will have to test the REST API from this dynamic cli. Let's take an example - I run the server on my laptop. So rather than opening POSTMAN or third-party tool. I'll user DynamicCLI in the terminal to test my REST API endpoints

**Comment by yasht01** [comment]
Hey, if possible, can the mentors add the GSSoC label?

**Comment by yasht01** [comment]
@GouravSardana can you suggest me any other issue I can work on?

**Comment by anshsrtv** [comment]
@yasht01 We have two issues (#45 & #50) available. Can you try any of those?
