### ISSUE TITLE
Separating CLI code from main code

### ISSUE THREAD

**Issue by lakshyabatman** [IndianOpenSourceFoundation/dynamic-cli#8]
### CLI related code should be in different file and core code in other files.
Type - Refactor

**Comment by RachitG001** [comment]
Assign me this task

**Comment by lakshyabatman** [comment]
Awesome.

**Comment by lakshyabatman** [comment]
Contributors, please assign this task to @RachitG001 , with this issue solved we can have cli code decoupled with core code, and adding additional features will be easier.

**Comment by GouravSardana** [comment]
@RachitG001 , I assigned this task. You can work on it

**Comment by RachitG001** [comment]
@GouravSardana I have raised the pr. Can you review it?

**Comment by GouravSardana** [comment]
Awesome @RachitG001 . You can also join our slack channel , Click [here](https://join.slack.com/t/iosf-india/shared_invite/zt-gt1emqhs-oSR5uUA89pfdAPMmdlB79A)

**Comment by GouravSardana** [comment]
I am closing this issue. You can reopen it, if you have any issues
