### ISSUE TITLE
Implement DELETE in dynamic to post the response from an API 

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#84]
This feature will include the following things -

1. Once a user will enter dynamic -DELETE, it will ask for a URL to put and the default URL would be 127.0.0.1:8000 and it will ask for the endpoint or you can put it directly in the URL itself
2. It will ask for headers then it will ask for payloads
3.  Optional param - User-Agent
4. It will build on top of CURL or Request
5. The output will get in JSON with proper syntax highlighter.

Example -
- dynamic -DELETE
- Enter the URL with endpoint - [press enter - default would be 127.0.0.1:800]
- Headers - Enter headers
- User Agent [Optional]
- Codes => 200 (OK). 404 (Not Found), if ID not found or invalid.
Posting (loading emoji)

```

{
json output
}

```

**Comment by reshchat** [comment]
Hi @GouravSardana can I take up this issue?

**Comment by subhangi2731** [comment]
@anshsrtv please assign this issue to me

**Comment by subhangi2731** [comment]
@GouravSardana please assign this issue to me

**Comment by harshakhmk** [comment]
I would like to take up this issue, can raise an MR soon

**Comment by GouravSardana** [comment]
Yes please work on it @harshakhmk

**Comment by harshakhmk** [comment]
Doesn't it have widows support
![windows-issue](https://user-images.githubusercontent.com/56113657/120926428-6eebc180-c6fa-11eb-965e-7754125c73ba.png)

**Comment by GouravSardana** [comment]
You can use these [things](https://itsfoss.com/run-linux-commands-in-windows/) for now. We are looking into it for windows support.
@pranavbaburaj can help you setup

**Comment by harshakhmk** [comment]
I tried the above ways but getting the same error, I think those are just running for commands and not manipulate the internal functionalities, working with basic commands like ``` ls, cat, copy``` etc works fine but this command has to do something with internal functionality of Linux os, so testing would this seem difficult, I will raise an MR following the code guidelines and flow of codebase can you review it and test it on your pc
Also after making the changes to the code, do I need to run any commands for formatting the code like black formatting
@GouravSardana

**Comment by pranavbaburaj** [comment]
> I tried the above ways but getting the same error, I think those are just running for commands and not manipulate the internal functionalities, working with basic commands like ` ls, cat, copy` etc works fine but this command has to do something with internal functionality of Linux os, so testing would this seem difficult, I will raise an MR following the code guidelines and flow of codebase can you review it and test it on your pc
> Also after making the changes to the code, do I need to run any commands for formatting the code like black formatting
> @GouravSardana

Sorry @harshakhmk, Sorry for the inconvenience, dynamic cli is at present not supported for windows. Contributors using windows are recommended to use [gitpod](http://gitpod.io/). Gitpod is an online vscode environment that runs on Linux. 

We are trying to find a module which supports windows. If you have any recommendations, please contribute your ideas [here](https://github.com/IndianOpenSourceFoundation/dynamic-cli/discussions/97)
