### ISSUE TITLE
Navigate the questions list through arrow keys and exit with 'Esc' key

### ISSUE THREAD

**Issue by NamamiShanker** [IndianOpenSourceFoundation/dynamic-cli#87]
## 💥 Proposal

The Dynamic now shows multiple relevant questions accessible by their question number. For ease of use, enable the user to cycle through questions with arrow keys instead. Instead of entering 0, allow the user to exit with Esc key.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/IndianOpenSourceFoundation/dynamic-cli/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes I have read it.

Allow me to work on this issue if it is selected.

**Comment by GouravSardana** [comment]
@NamamiShanker I just posted this in the comment of #82. Please work on it and your code is conflicting with the prompt-toolkit version. Fix that as well.

**Comment by NamamiShanker** [comment]
I have added PR #89 for this issue. Please review it.
